// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFW0DRTPK9pU6ep0JnCFiPb5C4RzDWdl4',
    appId: '1:476138765168:web:fb003c756359310a1fedb5',
    messagingSenderId: '476138765168',
    projectId: 'q-breakerapp',
    authDomain: 'q-breakerapp.firebaseapp.com',
    storageBucket: 'q-breakerapp.appspot.com',
    measurementId: 'G-D4ZE1BD2M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsLWQvemZnuFIWRMDrXtUXHbwS8rqQ3g',
    appId: '1:476138765168:android:fdfcdaeda41d73521fedb5',
    messagingSenderId: '476138765168',
    projectId: 'q-breakerapp',
    storageBucket: 'q-breakerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANA70r1jBzzcOzvXLGBnPg1o_956uhO0U',
    appId: '1:476138765168:ios:6783883fc078d1491fedb5',
    messagingSenderId: '476138765168',
    projectId: 'q-breakerapp',
    storageBucket: 'q-breakerapp.appspot.com',
    iosBundleId: 'com.example.qBreakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANA70r1jBzzcOzvXLGBnPg1o_956uhO0U',
    appId: '1:476138765168:ios:6783883fc078d1491fedb5',
    messagingSenderId: '476138765168',
    projectId: 'q-breakerapp',
    storageBucket: 'q-breakerapp.appspot.com',
    iosBundleId: 'com.example.qBreakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFW0DRTPK9pU6ep0JnCFiPb5C4RzDWdl4',
    appId: '1:476138765168:web:e681d029e2c66c351fedb5',
    messagingSenderId: '476138765168',
    projectId: 'q-breakerapp',
    authDomain: 'q-breakerapp.firebaseapp.com',
    storageBucket: 'q-breakerapp.appspot.com',
    measurementId: 'G-59YRVRY1KH',
  );
}
